# Generated by Django 5.1.1 on 2024-10-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_course_fields_of_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fields_of_study',
            new_name='field_of_study',
        ),
    ]
