# Generated by Django 5.1.1 on 2024-10-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_prerequisites_course_prerequisites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prerequisites',
            new_name='Prerequisite',
        ),
    ]
