# Generated by Django 5.1.1 on 2024-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_enrollment_completed_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
