# Generated by Django 5.1.1 on 2024-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_lesson_homework_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/'),
        ),
    ]
