# Generated by Django 5.1.1 on 2024-10-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_lesson_is_complete_lessoncompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_lessons',
        ),
    ]
