# Generated by Django 5.1.1 on 2024-10-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_enrollment_completed_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.ManyToManyField(through='users.LessonCompletion', to='users.lesson'),
        ),
    ]
