# Generated by Django 5.1.1 on 2024-11-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_quiz_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_answers',
            field=models.ManyToManyField(blank=True, to='users.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='users.question'),
        ),
        migrations.AlterField(
            model_name='studentquizsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
