# Generated by Django 5.1.1 on 2024-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_studentanswer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizsession',
            name='correct_answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
