# Generated by Django 5.1.1 on 2024-11-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_studentquizsession_correct_answer_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name_plural': 'Field of Studies'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
