# Generated by Django 5.1.1 on 2024-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_fieldofstudy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_answers',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
