# Generated by Django 5.1.1 on 2024-11-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_studentanswer_selected_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquizsession',
            name='current_question_index',
        ),
    ]
