# Generated by Django 5.1.1 on 2024-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_studentquizsession_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizsession',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
