# Generated by Django 5.1.1 on 2024-12-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_course_field_of_study_course_field_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='feedback',
        ),
    ]
