# Generated by Django 5.1.1 on 2024-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_lessoncompletion_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizsession',
            name='solved_in',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
