# Generated by Django 5.1.1 on 2025-02-26 10:25

import capstone.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_studentquizsession_solved_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='file',
            field=models.FileField(storage=capstone.storage_backends.MediaStorage(), upload_to='assignment_files/'),
        ),
    ]
