# Generated by Django 5.1.1 on 2025-02-26 11:49

import capstone.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_studentanswer_selected_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='file',
            field=models.FileField(storage=capstone.storage_backends.MediaStorage(), upload_to='media/assignment_files/'),
        ),
    ]
