# Generated by Django 5.1.1 on 2025-02-26 12:40

import capstone.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_studentassignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='file',
            field=models.FileField(storage=capstone.storage_backends.MediaStorage(), upload_to='assignment_files/'),
        ),
    ]
