# Generated by Django 5.1.1 on 2025-02-27 11:46

import capstone.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_studentassignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=capstone.storage_backends.MediaStorage(), upload_to='lesson_pdfs/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=capstone.storage_backends.MediaStorage(), upload_to='lesson_videos/'),
        ),
    ]
